//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actividad_CRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        public int IDInventario { get; set; }
        public Nullable<int> IDProducto { get; set; }
        public Nullable<int> CantidadEnStock { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}
