//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actividad_CRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int IDUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public string Contraseña { get; set; }
        public string TipoUsuario { get; set; }
        public Nullable<int> IDEmpleado { get; set; }
    
        public virtual Empleados Empleados { get; set; }
    }
}
